name: helppsico_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  file_picker: ^6.1.1
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  universal_html: ^2.2.4


  mockito: ^5.4.2
  build_runner: ^2.4.6
  coverage: ^1.6.3
  bloc_test: ^9.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
