name: helppsico_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  flutter_secure_storage: ^9.0.0
  jwt_decoder: ^2.0.1
  flutter_launcher_icons: ^0.13.1
  universal_html: ^2.2.4
  mockito: ^5.4.2
  build_runner: ^2.4.6
  coverage: 1.12.0
  bloc_test: ^9.0.3
  intl: ^0.20.2
  flutter_local_notifications: ^19.1.0
  shared_preferences: ^2.5.3
  timezone: ^0.10.1
  uuid: ^3.0.6
  get_it: ^8.0.3
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo/logoroxa.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
